# Sterling's library: the key ideas of the most important business and money books and thinkers,
# summarized in our own words (no book text). Build: python3 library.py > ../library.json
import json, sys

TOPICS = ["offers", "pricing", "marketing", "ads", "copywriting", "brand", "sales", "customers", "startup",
          "ecommerce", "strategy", "systems", "money", "investing", "mindset", "habits", "negotiation", "leadership", "story", "psychology"]

BOOKS = [
  ("hormozi-offers", "$100M Offers", "Alex Hormozi", 2021, ["offers", "pricing", "sales"], True,
   "Make an offer so good people feel stupid saying no.",
   ["Value = (dream outcome × how likely it feels) ÷ (time it takes × effort and sacrifice). Raise the top, shrink the bottom.",
    "Sell to a starving crowd: people with a painful problem, money to spend, easy to reach, in a growing market.",
    "Don't compete on price. Charge more and deliver far more; low prices attract the worst customers.",
    "Stack bonuses, add guarantees, scarcity and urgency, and name the offer clearly."],
   "Use it when you decide what to sell and how to price it."),
  ("hormozi-leads", "$100M Leads", "Alex Hormozi", 2023, ["marketing", "ads", "sales"], True,
   "There are only four ways to get customers: warm outreach, cold outreach, free content, and paid ads.",
   ["Start with warm outreach (people who know you), then add content, cold outreach and ads as you grow.",
    "Give away so much value for free that people want to pay for more.",
    "A 'lead magnet' solves one small problem for free and shows the next problem your product solves.",
    "Do more of what works. Volume beats cleverness at the start (the 'rule of 100': 100 actions a day)."],
   "Use it when you need more people to see and buy your product."),
  ("lean-startup", "The Lean Startup", "Eric Ries", 2011, ["startup", "customers", "strategy"], True,
   "Build the smallest thing that tests your idea, measure what happens, learn, repeat.",
   ["Build–Measure–Learn: every product is an experiment until customers prove it works.",
    "A minimum viable product (MVP) is the cheapest way to test if people will actually pay.",
    "Measure real behavior (sales, repeat buyers), not 'vanity metrics' like likes.",
    "Pivot or persevere: change direction when the data says so, not when you get bored."],
   "Use it when testing products in your store: small tests before big spending."),
  ("mom-test", "The Mom Test", "Rob Fitzpatrick", 2013, ["customers", "startup", "sales"], True,
   "Everyone lies to you about your idea to be nice, so ask about their life, not your idea.",
   ["Ask about what people did in the past, not what they would do in the future.",
    "Talk about their problem and what they already spent money on to solve it.",
    "Compliments are worthless; commitments (time, money, a pre-order) are real signals."],
   "Use it before choosing a product: talk to real buyers first."),
  ("zero-to-one", "Zero to One", "Peter Thiel", 2014, ["strategy", "startup"], False,
   "The best businesses create something new instead of copying what already exists.",
   ["Competition kills profits; aim to be the only one doing your thing for a specific group.",
    "Start small and dominate a niche, then expand.",
    "Ask: what important truth do very few people agree with you on?"],
   "Use it when thinking about your bigger, long-term business."),
  ("e-myth", "The E-Myth Revisited", "Michael E. Gerber", 1995, ["systems", "leadership"], False,
   "Work on your business, not just in it: build systems so it runs without you doing everything.",
   ["Most people who start businesses are technicians who end up with a job, not a business.",
    "Write down how every task is done, so someone else (or software) can do it.",
    "Imagine your business as a franchise prototype: the same great result every time."],
   "Use it when the store grows and you can't do everything yourself."),
  ("profit-first", "Profit First", "Mike Michalowicz", 2014, ["money", "systems"], True,
   "Take your profit first, then run the business on what's left.",
   ["Sales − Profit = Expenses, not Sales − Expenses = Profit.",
    "Split money into separate accounts right away: profit, owner pay, tax, operating costs.",
    "Having less to spend forces you to be creative and efficient."],
   "Use it as soon as money starts coming in, so you keep some of it."),
  ("psychology-of-money", "The Psychology of Money", "Morgan Housel", 2020, ["money", "mindset", "investing"], True,
   "Doing well with money is more about behavior than intelligence.",
   ["Compounding is the most powerful force in money: time matters more than returns.",
    "Wealth is what you don't see: the money you didn't spend.",
    "'Enough' is a skill. Never risk what you have and need for what you don't have and don't need.",
    "Leave room for error: save more than seems necessary."],
   "Use it to build good money habits for life."),
  ("richest-man-babylon", "The Richest Man in Babylon", "George S. Clason", 1926, ["money", "mindset"], True,
   "Keep at least a tenth of everything you earn. Pay yourself first.",
   ["Save at least 10% of all income before spending anything.",
    "Make your saved money work: invest it so it earns more money.",
    "Guard your savings from risky 'too good to be true' deals.",
    "Increase your ability to earn by learning skills."],
   "Use it as the simplest money rule to start with."),
  ("rich-dad", "Rich Dad Poor Dad", "Robert Kiyosaki", 1997, ["money", "mindset"], True,
   "The rich buy assets that put money in their pocket; most people buy liabilities that take it out.",
   ["An asset puts money in your pocket; a liability takes money out.",
    "Learn financial skills early: school rarely teaches them.",
    "Work to learn, not only to earn."],
   "Use it for the asset vs liability mindset.",
   "Great for mindset, but some advice (like heavy use of debt) is risky. Take the mindset, not the tactics."),
  ("millionaire-next-door", "The Millionaire Next Door", "Thomas J. Stanley & William D. Danko", 1996, ["money", "mindset"], False,
   "Most real millionaires live below their means and look ordinary.",
   ["Spending on status symbols is the enemy of becoming wealthy.",
    "Wealth comes from earning well, spending less, and investing the difference for years."],
   "Use it when you start making money and feel like spending it on flashy things."),
  ("intelligent-investor", "The Intelligent Investor", "Benjamin Graham", 1949, ["investing", "money"], False,
   "Invest with a margin of safety, and don't let the market's mood control you.",
   ["Think of the market as 'Mr. Market': a moody partner offering prices every day. Use him, don't obey him.",
    "Buy with a margin of safety: pay much less than something is worth.",
    "Investing is thorough analysis, safety of principal, and an adequate return; anything else is speculation."],
   "Use it when you're ready to invest profits (with a parent, since you're under 18)."),
  ("bogle", "The Little Book of Common Sense Investing", "John C. Bogle", 2007, ["investing", "money"], True,
   "Buy the whole market cheaply with index funds and hold for decades.",
   ["Most professional investors don't beat the market after fees.",
    "Low-cost index funds let you own a piece of every big company.",
    "Costs and taxes matter enormously over time; keep them low."],
   "Use it for the simplest long-term investing plan."),
  ("influence", "Influence", "Robert Cialdini", 1984, ["sales", "marketing", "copywriting"], True,
   "People say yes for predictable reasons.",
   ["Reciprocity: give first and people want to give back.",
    "Commitment and consistency: small yeses lead to bigger ones.",
    "Social proof: people follow what others do (reviews, numbers of buyers).",
    "Authority, liking, scarcity and unity also push people to say yes. Use them honestly."],
   "Use it on product pages and ads: reviews, limited stock, guarantees."),
  ("never-split", "Never Split the Difference", "Chris Voss", 2016, ["negotiation", "sales"], True,
   "Negotiation is about understanding the other side's emotions, not tricking them.",
   ["Tactical empathy: show you understand how they feel ('It seems like…').",
    "Ask calibrated 'how' and 'what' questions: 'How am I supposed to do that?'",
    "Mirroring: repeat their last few words to get them to say more.",
    "Aim for 'That's right', not a quick 'yes'."],
   "Use it when talking to suppliers about prices and shipping."),
  ("carnegie", "How to Win Friends and Influence People", "Dale Carnegie", 1936, ["sales", "leadership", "mindset"], True,
   "People care most about themselves: show real interest in them.",
   ["Remember names and make people feel important, sincerely.",
    "Don't criticize, condemn or complain.",
    "Talk in terms of what the other person wants."],
   "Use it with customers, suppliers, partners and everyone else."),
  ("storybrand", "Building a StoryBrand", "Donald Miller", 2017, ["brand", "marketing", "copywriting", "story"], False,
   "Your customer is the hero of the story; your brand is the guide.",
   ["Clearly say what you offer, how it makes life better, and what to do to buy.",
    "Every customer story: a hero with a problem meets a guide who gives a plan and calls them to act.",
    "Confusing messages lose sales. Clarity wins."],
   "Use it when writing your store's homepage and product pages."),
  ("this-is-marketing", "This Is Marketing", "Seth Godin", 2018, ["marketing", "brand"], False,
   "Find the smallest group of people you can truly delight, and serve them.",
   ["People like us do things like this: marketing is about belonging.",
    "Pick your smallest viable audience instead of trying to reach everyone.",
    "Marketing is helping people become who they want to become."],
   "Use it when choosing your niche and your personal brand's audience."),
  ("purple-cow", "Purple Cow", "Seth Godin", 2003, ["marketing", "brand", "ecommerce"], False,
   "Be remarkable (worth making a remark about) or be invisible.",
   ["Safe and boring products get ignored.",
    "Design something so interesting that people talk about it."],
   "Use it to test product ideas: would anyone share this?"),
  ("contagious", "Contagious", "Jonah Berger", 2013, ["marketing", "ads", "brand"], False,
   "Things spread when they hit six triggers: social currency, triggers, emotion, public, practical value, stories.",
   ["People share what makes them look good (social currency).",
    "High-arousal emotions (awe, excitement, even anger) get shared most.",
    "Useful tips and stories carry a product along with them."],
   "Use it when planning viral content and TikTok ads."),
  ("made-to-stick", "Made to Stick", "Chip Heath & Dan Heath", 2007, ["copywriting", "marketing", "story"], False,
   "Sticky ideas are Simple, Unexpected, Concrete, Credible, Emotional Stories.",
   ["Find the core of your message and cut the rest.",
    "Concrete details beat abstract claims ('holds 20 kg', not 'super strong')."],
   "Use it when writing ad hooks and product descriptions."),
  ("ogilvy", "Ogilvy on Advertising", "David Ogilvy", 1983, ["ads", "copywriting"], False,
   "Advertising should sell, not just look creative.",
   ["The headline does most of the work: most people read only the headline.",
    "Specific facts sell better than general claims.",
    "Test everything and keep what sells."],
   "Use it when writing ads and product titles."),
  ("breakthrough-advertising", "Breakthrough Advertising", "Eugene Schwartz", 1966, ["copywriting", "ads"], False,
   "You can't create desire; you can only channel desire that already exists.",
   ["Match your message to how aware the customer is: of the problem, of solutions, of your product.",
    "The more crowded the market, the more specific and new your promise must be."],
   "Use it when your ads stop working and you need a new angle."),
  ("traction", "Traction", "Gabriel Weinberg & Justin Mares", 2015, ["marketing", "startup", "ads"], False,
   "There are 19 ways to get customers; test several and double down on the best one.",
   ["Bullseye: brainstorm all channels, test the most promising 3 cheaply, focus on the winner.",
    "Spend half your time on getting customers, not just on the product."],
   "Use it to choose where to find customers beyond one ad platform."),
  ("good-to-great", "Good to Great", "Jim Collins", 2001, ["strategy", "leadership"], False,
   "Great companies focus on what they can be best at, love doing, and can make money from.",
   ["The Hedgehog Concept: the overlap of passion, being best in the world, and your economic engine.",
    "The flywheel: success comes from consistent pushes in one direction, not one big moment.",
    "First who, then what: the right people matter before the right plan."],
   "Use it when building a bigger business later."),
  ("hard-things", "The Hard Thing About Hard Things", "Ben Horowitz", 2014, ["leadership", "mindset", "startup"], False,
   "There's no recipe for hard problems; the job is to keep going and make the tough calls.",
   ["The struggle is normal; every founder feels it.",
    "Tell the truth fast, especially bad news."],
   "Use it when things go wrong and you want to quit."),
  ("shoe-dog", "Shoe Dog", "Phil Knight", 2016, ["story", "startup", "mindset"], True,
   "Nike started as a young guy selling imported shoes from his car. Keep going.",
   ["Phil Knight began by importing shoes from Japan and selling them himself: a lot like dropshipping.",
    "Cash flow nearly killed Nike many times: growing fast needs money management.",
    "Build a brand people love, not just a product."],
   "Use it for inspiration: the most exciting business story for a young founder."),
  ("four-hour-workweek", "The 4-Hour Workweek", "Tim Ferriss", 2007, ["systems", "ecommerce", "mindset"], False,
   "Design a business that runs without you, so you can live where and how you want.",
   ["DEAL: Definition, Elimination, Automation, Liberation.",
    "80/20: find the 20% of work that gives 80% of results and cut the rest.",
    "A 'muse' is a small automated product business that pays for your freedom."],
   "Use it when you want the business to fund travel and freedom."),
  ("fastlane", "The Millionaire Fastlane", "MJ DeMarco", 2011, ["mindset", "startup", "money"], False,
   "Wealth comes fastest from building a business that can reach many people, not from saving a salary for 40 years.",
   ["CENTS: Control, Entry (hard to copy), Need, Time (runs without you), Scale.",
    "Solve a real need for many people and money follows."],
   "Use it to judge whether a business idea can grow big.",
   "Some parts are harsh about 'slow' saving; long-term investing still matters."),
  ("naval", "The Almanack of Naval Ravikant", "Eric Jorgenson", 2020, ["mindset", "money", "strategy"], True,
   "Seek wealth, not money or status: own things that earn while you sleep.",
   ["Specific knowledge: what you're uniquely good at and love, which can't easily be taught.",
    "Leverage: code, media (content) and capital let small teams have huge results.",
    "Play long-term games with long-term people: trust compounds like money.",
    "You won't get rich renting out your time."],
   "Use it for the big picture: why a personal brand is powerful."),
  ("personal-mba", "The Personal MBA", "Josh Kaufman", 2010, ["strategy", "systems", "sales", "marketing"], True,
   "Every business does five things: creates value, markets it, sells it, delivers it, and manages the money.",
   ["If any of the five parts is missing, it's not a business.",
    "You can learn most of business school from books, cheaply."],
   "Use it as a map of the whole business."),
  ("built-to-sell", "Built to Sell", "John Warrillow", 2010, ["systems", "strategy"], False,
   "Build a business that could be sold one day, even if you never sell it.",
   ["Focus on one thing you do very well and can teach others to do.",
    "A business that depends on you is hard to sell and hard to enjoy."],
   "Use it when turning your store into a real brand."),
  ("company-of-one", "Company of One", "Paul Jarvis", 2019, ["strategy", "systems"], False,
   "Bigger isn't always better: a small, profitable business can give you freedom.",
   ["Grow only when growth makes the business better, not just bigger.",
    "Stay lean: fewer costs mean more profit and more freedom."],
   "Use it when deciding whether to hire or scale."),
  ("blue-ocean", "Blue Ocean Strategy", "W. Chan Kim & Renée Mauborgne", 2005, ["strategy"], False,
   "Don't fight in a crowded 'red ocean'; create new space where competition doesn't matter.",
   ["Eliminate, reduce, raise, create: change what your product offers compared to everyone else.",
    "Find what customers put up with and remove it."],
   "Use it when every product in your niche looks the same."),
  ("atomic-habits", "Atomic Habits", "James Clear", 2018, ["habits", "mindset"], True,
   "Tiny improvements, done every day, add up to huge results.",
   ["Get 1% better every day.",
    "Focus on systems (what you do daily) rather than goals.",
    "Make good habits obvious, attractive, easy and satisfying.",
    "Identity first: 'I'm the kind of person who logs my numbers every day.'"],
   "Use it to stick with training, logging and learning every day."),
  ("deep-work", "Deep Work", "Cal Newport", 2016, ["habits", "mindset"], False,
   "Focused, distraction-free work is rare and extremely valuable.",
   ["Block time with no phone and no notifications.",
    "Shallow busywork feels productive but moves little."],
   "Use it when you need to build something important after school."),
  ("principles", "Principles", "Ray Dalio", 2017, ["mindset", "leadership", "investing"], False,
   "Pain + reflection = progress. Write down your principles and improve them.",
   ["Embrace reality and deal with it.",
    "Be radically open-minded: look for where you might be wrong.",
    "Mistakes are lessons; write down what you learned."],
   "Use it when you make mistakes and want to learn faster."),
  ("show-your-work", "Show Your Work!", "Austin Kleon", 2014, ["brand", "marketing"], True,
   "Share your process as you learn, and an audience will find you.",
   ["You don't have to be a genius; share what you're learning.",
    "Teach what you know: it builds trust.",
    "Be consistent: share something small every day."],
   "Use it to start your personal brand right now, safely."),
  ("crushing-it", "Crushing It!", "Gary Vaynerchuk", 2018, ["brand", "marketing"], False,
   "Anyone can build a personal brand today by making lots of useful content on the right platforms.",
   ["Document, don't create: film your journey instead of inventing content.",
    "Pick platforms where your audience's attention is, and post a lot."],
   "Use it when you start your personal brand content."),

  # --- marketing classics ---
  ("scientific-advertising", "Scientific Advertising", "Claude C. Hopkins", 1923, ["ads", "copywriting", "marketing"], True,
   "Advertising is salesmanship in print, and every ad should be tested like an experiment.",
   ["Measure everything: track which ad brought which sale, and keep only what works.",
    "Be specific: exact numbers and details are believed; vague claims are ignored.",
    "Tell the story of how your product is made or why it's better; even ordinary facts sound special when nobody else says them.",
    "Offer samples or a small first step so people can try before committing."],
   "Use it before spending on ads: test small, keep the winners."),
  ("tested-advertising", "Tested Advertising Methods", "John Caples", 1932, ["copywriting", "ads"], False,
   "The headline decides whether an ad works; test headlines above everything else.",
   ["The best headlines appeal to self-interest, share news, or spark curiosity.",
    "Changing only the headline can make the same ad sell many times more.",
    "Write his most famous kind of headline: a before-and-after story ('They laughed when I sat down at the piano…')."],
   "Use it when writing ad hooks and product titles."),
  ("positioning", "Positioning: The Battle for Your Mind", "Al Ries & Jack Trout", 1981, ["brand", "marketing", "strategy"], True,
   "Win a place in the customer's mind by owning one simple word or idea.",
   ["People remember the first in a category much better than the best.",
    "If you can't be first in a category, create a new category you can be first in.",
    "Own one word (Volvo = safety). Trying to stand for everything means standing for nothing."],
   "Use it when naming your store and deciding what it's known for."),
  ("22-laws", "The 22 Immutable Laws of Marketing", "Al Ries & Jack Trout", 1993, ["marketing", "brand", "strategy"], False,
   "Marketing is a battle of perceptions, not products.",
   ["Law of leadership: it's better to be first than better.",
    "Law of focus: own a word in the prospect's mind.",
    "Law of sacrifice: to win, give something up (fewer products, a narrower audience)."],
   "Use it as a checklist when your marketing feels unfocused."),
  ("how-brands-grow", "How Brands Grow", "Byron Sharp", 2010, ["brand", "marketing", "ads"], False,
   "Brands grow by reaching more people and being easy to remember and easy to buy.",
   ["Mental availability: be the brand people think of in buying moments.",
    "Physical availability: be easy to find and buy everywhere your buyers are.",
    "Most sales come from many light buyers, not a few loyal fans: keep reaching new people.",
    "Use distinctive brand assets (colors, logo, sound) consistently so people recognize you instantly."],
   "Use it when building a brand that lasts, beyond one viral product."),
  ("alchemy", "Alchemy", "Rory Sutherland", 2019, ["psychology", "marketing", "brand"], True,
   "People aren't logical; small changes in how something feels can matter more than big changes in what it is.",
   ["The opposite of a good idea can also be a good idea: test illogical things.",
    "Perceived value is real value to the customer: packaging, names and stories change how products feel.",
    "Costly signals build trust: effort, guarantees and quality details show you believe in the product.",
    "Reduce worry: a clear delivery time or tracking can matter more than faster shipping."],
   "Use it to find cheap, clever ways to make your product feel more valuable."),
  ("dotcom-secrets", "DotCom Secrets", "Russell Brunson", 2015, ["marketing", "sales", "ecommerce", "offers"], False,
   "Don't sell one product; build a funnel that takes buyers step by step to bigger offers.",
   ["The value ladder: a free or cheap first offer, then better and more valuable ones.",
    "Hook, story, offer: grab attention, tell a story that builds belief, then make the offer.",
    "Add order bumps and upsells: most profit comes after the first purchase."],
   "Use it to raise how much each customer spends in your store."),
  ("boron-letters", "The Boron Letters", "Gary Halbert", 1984, ["copywriting", "marketing", "sales"], False,
   "The most important thing is a starving crowd: people who badly want what you sell.",
   ["Pick the hungry market first; great copy can't save a product nobody wants.",
    "Copy great ads by hand to learn how they're built.",
    "Stay fit and write every day: discipline is part of the craft."],
   "Use it to learn copywriting and choose markets. Letters he wrote to his son."),
  ("cashvertising", "Cashvertising", "Drew Eric Whitman", 2008, ["psychology", "copywriting", "ads"], False,
   "Tap the deep desires everyone shares and your ads work better.",
   ["The 'Life-Force 8': survival, enjoying food and drink, freedom from fear and pain, attraction, comfort, winning, protecting loved ones, and being approved of.",
    "Fear works only when paired with a clear, easy solution.",
    "Specific, vivid words let people picture themselves using the product."],
   "Use it when an ad feels flat and needs a stronger emotional reason to buy."),
  ("sugarman", "The Adweek Copywriting Handbook", "Joseph Sugarman", 2006, ["copywriting", "psychology"], False,
   "Every sentence has one job: get the next sentence read.",
   ["The slippery slide: short first lines pull readers down the page.",
    "Use psychological triggers like curiosity, proof and a sense of belonging.",
    "Keep the reader nodding 'yes' as they read."],
   "Use it when writing product descriptions and emails."),
  ("guerrilla-marketing", "Guerrilla Marketing", "Jay Conrad Levinson", 1984, ["marketing", "brand"], True,
   "Use time, energy and imagination instead of a big budget.",
   ["Small businesses win with creativity and consistency, not money.",
    "Build relationships and follow up with customers.",
    "Many small, cheap marketing actions add up."],
   "Use it while your budget is small: perfect for starting with $850."),
  ("hooked", "Hooked", "Nir Eyal", 2014, ["psychology", "customers"], False,
   "Products people use again and again follow a loop: trigger, action, variable reward, investment.",
   ["Triggers bring people back; rewards that change a little keep it interesting.",
    "When users invest something (data, effort, content) they're more likely to return.",
    "Use it ethically: build habits that help people, not ones that trap them."],
   "Use it to get repeat customers (emails, loyalty rewards, new drops)."),
  ("growth-hacker", "Growth Hacker Marketing", "Ryan Holiday", 2013, ["marketing", "startup"], False,
   "The best marketing is built into the product itself.",
   ["Find product-market fit first; marketing a product people don't want is wasted money.",
    "Make it easy and rewarding to share (referrals, share buttons, unboxing moments).",
    "Target a small group of early fans before trying to reach everyone."],
   "Use it to design word of mouth into your store."),
  ("everybody-writes", "Everybody Writes", "Ann Handley", 2014, ["copywriting", "brand"], False,
   "Good writing is a skill anyone can learn, and it sells.",
   ["Write for one reader, like you're talking to a friend.",
    "The first draft is for you; rewrite to make it clear and short."],
   "Use it for captions, emails and your personal brand posts."),
  ("poor-charlie", "Poor Charlie's Almanack", "Charlie Munger (ed. Peter Kaufman)", 2005, ["mindset", "investing", "strategy"], False,
   "Learn the big ideas from many subjects and use them together to think clearly.",
   ["Mental models: a latticework of ideas from many fields.",
    "Invert, always invert: ask how to fail, then avoid it.",
    "Know your circle of competence and stay inside it."],
   "Use it to make better decisions of any kind."),
]

MINDS = [
  ("buffett", "Warren Buffett", "Investor, Berkshire Hathaway", ["investing", "money", "strategy", "mindset"],
   "Buy wonderful businesses at fair prices and hold them for a very long time.",
   ["Rule No. 1: never lose money. Rule No. 2: never forget rule No. 1.",
    "Look for a moat: something that protects a business from competitors.",
    "Be fearful when others are greedy and greedy when others are fearful.",
    "Stay inside your circle of competence."],
   "Started selling gum, soda and newspapers as a kid; bought his first stock at 11."),
  ("munger", "Charlie Munger", "Buffett's partner", ["mindset", "investing", "strategy"],
   "Avoid stupidity rather than trying to be brilliant.",
   ["Invert: figure out what would ruin you and avoid it.",
    "Use mental models from many fields.",
    "Be patient: the big money is in waiting."], ""),
  ("naval-mind", "Naval Ravikant", "Entrepreneur and investor", ["mindset", "money", "brand"],
   "Build or buy equity in things that earn without your time.",
   ["Specific knowledge + leverage + accountability = wealth.",
    "Read what you love until you love to read.",
    "Productize yourself."], ""),
  ("hormozi-mind", "Alex Hormozi", "Entrepreneur and author", ["offers", "sales", "marketing"],
   "Make offers so good people feel stupid saying no, then get in front of a lot of people.",
   ["Volume negates luck: do more reps than anyone.",
    "Price on value, not on cost.",
    "Give value for free until people ask how to pay you."], ""),
  ("paul-graham", "Paul Graham", "Y Combinator co-founder, essayist", ["startup", "customers"],
   "Make something people want.",
   ["Do things that don't scale at the start: talk to every customer yourself.",
    "Launch fast and improve based on real users.",
    "The best ideas often look like toys at first."], ""),
  ("bezos", "Jeff Bezos", "Founder of Amazon", ["ecommerce", "customers", "strategy"],
   "Obsess over customers, not competitors.",
   ["Focus on what won't change: people will always want low prices, fast delivery and big selection.",
    "Regret minimization: at 80, which choice will you regret not making?",
    "Stay 'Day 1': keep the energy of a startup."], "Started Amazon selling books from his garage."),
  ("jobs", "Steve Jobs", "Co-founder of Apple", ["brand", "strategy", "leadership"],
   "Focus means saying no to a hundred good ideas.",
   ["Simplicity is the ultimate sophistication.",
    "Start with the customer experience and work back to the technology.",
    "Stay hungry, stay foolish."], ""),
  ("musk", "Elon Musk", "Tesla, SpaceX", ["mindset", "strategy"],
   "Reason from first principles, not by copying what others do.",
   ["Break a problem down to the basic facts and rebuild it from there.",
    "Work on things that matter at huge scale."],
   "Sold a video game he coded at 12 for about $500."),
  ("blakely", "Sara Blakely", "Founder of Spanx", ["startup", "mindset", "brand"],
   "Start with the little money you have, and see failure as a sign you tried.",
   ["Started Spanx with about $5,000 of savings.",
    "Don't share your idea with doubters too early; build first.",
    "Her dad asked every night: 'What did you fail at this week?'"], ""),
  ("mrbeast", "MrBeast (Jimmy Donaldson)", "Creator and entrepreneur", ["brand", "marketing", "story"],
   "Obsess over what makes people click and keep watching, then reinvest everything.",
   ["The title and thumbnail decide if anyone watches: make them irresistible.",
    "Reinvest profits into making the next thing better.",
    "He studied his craft for years before it took off."],
   "Started posting on YouTube at 13.", "marketing"),
  ("vaynerchuk", "Gary Vaynerchuk", "Entrepreneur, VaynerMedia", ["brand", "marketing", "mindset"],
   "Attention is the asset: go where people's attention is now.",
   ["Document your journey instead of trying to look perfect.",
    "Patience plus hard work beats shortcuts.",
    "Started a trading-card and lemonade hustle as a kid."], ""),
  ("godin", "Seth Godin", "Marketer and author", ["marketing", "brand"],
   "Be remarkable to a small group who cares, instead of average to everyone.",
   ["Find your smallest viable audience.",
    "Ship your work, even if it isn't perfect."], "", "marketing"),
  ("thiel-mind", "Peter Thiel", "PayPal co-founder, investor", ["strategy", "startup"],
   "Competition is for losers: build something unique.",
   ["Dominate a small market first.",
    "Look for secrets: truths few people see."], ""),
  ("dalio-mind", "Ray Dalio", "Founder of Bridgewater", ["mindset", "investing"],
   "Pain plus reflection equals progress.",
   ["Write down your principles.",
    "Diversify: don't bet everything on one thing."], ""),
  ("housel", "Morgan Housel", "Author of The Psychology of Money", ["money", "mindset"],
   "Saving money is the gap between your ego and your income.",
   ["Time is the most powerful force in money.",
    "Stay reasonable, not perfectly rational."], ""),
  ("knight", "Phil Knight", "Founder of Nike", ["story", "brand", "startup"],
   "Let everyone else call your idea crazy. Just keep going.",
   ["Began by importing shoes and selling from his car.",
    "Built a brand around athletes and emotion, not just shoes."], ""),
  ("walton", "Sam Walton", "Founder of Walmart", ["ecommerce", "customers", "pricing"],
   "Keep costs low and pass the savings to customers.",
   ["Visit competitors and copy their best ideas.",
    "Listen to everyone, especially the people on the front line."], "Delivered newspapers and sold magazines as a kid."),

  # --- marketing geniuses (group "marketing") ---
  ("ogilvy-mind", "David Ogilvy", "The father of advertising", ["ads", "copywriting", "brand"],
   "The consumer isn't a moron; she's your wife. Respect your customer and give them facts.",
   ["On average, five times as many people read the headline as the body copy.",
    "Research first: know the product and the customer better than anyone.",
    "Big ideas sell: a clear promise, told in a memorable way."],
   "Sold cooking stoves door to door as a young man and wrote a famous sales guide about it.", "marketing"),
  ("schwartz-mind", "Eugene Schwartz", "Legendary copywriter", ["copywriting", "psychology"],
   "Copy can't create desire; it can only take a desire that already exists and point it at your product.",
   ["Match your message to how aware the customer is.",
    "In crowded markets, make a bigger or more specific claim, or a new mechanism."], "", "marketing"),
  ("hopkins-mind", "Claude Hopkins", "Pioneer of tested advertising", ["ads", "copywriting"],
   "Treat advertising like science: test, measure, keep what sells.",
   ["Use coupons and tracking so every ad shows its results.",
    "Explain how your product is made or why it's better, even if competitors do the same."], "", "marketing"),
  ("halbert-mind", "Gary Halbert", "Direct-response copywriter", ["copywriting", "marketing", "sales"],
   "Find a starving crowd first; the market matters more than the copy or the product.",
   ["Personal, conversational letters beat slick corporate ads.",
    "Write every day and study great ads by copying them out."],
   "His 'coat of arms' letter is one of the most mailed sales letters in history.", "marketing"),
  ("kennedy-mind", "Dan Kennedy", "Direct-response marketer", ["marketing", "sales", "copywriting"],
   "Every ad should ask for a response you can measure: a call, a click, a sale.",
   ["Message, market, media: the right message to the right people in the right place.",
    "Follow up many times; most sales happen after the first contact."], "", "marketing"),
  ("brunson-mind", "Russell Brunson", "Co-founder of ClickFunnels", ["marketing", "sales", "offers"],
   "Hook, story, offer: grab attention, tell a story, then make an offer they can't refuse.",
   ["Build a value ladder from a cheap first offer to premium ones.",
    "Be an 'attractive character': share your real story with your audience."],
   "Started as a college wrestler selling a DVD on how to build potato guns online.", "marketing"),
  ("sutherland-mind", "Rory Sutherland", "Vice chairman of Ogilvy UK", ["psychology", "marketing", "brand"],
   "Logic is overrated in marketing; small psychological changes can beat expensive improvements.",
   ["Change how something is perceived before changing what it is.",
    "Test counter-intuitive ideas; your competitors won't."], "", "marketing"),
  ("sharp-mind", "Byron Sharp", "Marketing scientist", ["brand", "marketing"],
   "Brands grow by reaching more buyers and being easy to remember and buy.",
   ["Don't obsess over loyalty; keep reaching new light buyers.",
    "Be consistent with your colors, logo and style so people recognize you."], "", "marketing"),
  ("ries-trout-mind", "Al Ries & Jack Trout", "Creators of 'positioning'", ["brand", "strategy"],
   "Marketing happens in the customer's mind: own one simple word there.",
   ["Be first in a category, or create a new one.",
    "Sacrifice: focus beats trying to please everyone."], "", "marketing"),
  ("sugarman-mind", "Joe Sugarman", "Copywriter, BluBlocker sunglasses", ["copywriting", "psychology", "sales"],
   "The first sentence's job is to get the second sentence read.",
   ["Make the copy a slippery slide.",
    "Sell the emotion, justify with logic."],
   "Sold millions of BluBlocker sunglasses through ads he wrote himself.", "marketing"),
  ("levinson-mind", "Jay Conrad Levinson", "Father of guerrilla marketing", ["marketing"],
   "Out-think, don't out-spend: creativity beats budget.",
   ["Consistency and follow-up beat one big campaign."], "", "marketing"),
  ("wiebe-mind", "Joanna Wiebe", "Founder of Copyhackers, conversion copywriting", ["copywriting", "customers", "ecommerce"],
   "The best copy is found, not written: use your customers' own words.",
   ["Mine reviews (yours and competitors') for exact phrases buyers use.",
    "Write for one reader and one action per page."], "", "marketing"),
  ("carnegie-andrew", "Andrew Carnegie", "Industrialist and philanthropist", ["leadership", "money"],
   "Surround yourself with people smarter than you, and give back.",
   ["Spent the second half of his life giving his fortune away: libraries, schools.",
    "Put your eggs in one basket and watch that basket closely."], ""),
  ("franklin", "Benjamin Franklin", "Founder, printer, inventor", ["money", "habits"],
   "An investment in knowledge pays the best interest.",
   ["A penny saved is a penny earned.",
    "Daily self-review: he tracked 13 virtues every day."], ""),
  ("oprah", "Oprah Winfrey", "Media entrepreneur", ["brand", "mindset"],
   "Turn your real story into your brand, and own what you build.",
   ["Owning her show's production company made her a billionaire, not just being on TV.",
    "Authenticity builds trust with an audience."], ""),
]

out = []
for b in BOOKS:
    id_, name, by, year, topics, start, big, ideas, use = b[:9]
    note = b[9] if len(b) > 9 else ""
    assert all(t in TOPICS for t in topics), (id_, topics)
    out.append({"id": id_, "type": "book", "tab": "book", "name": name, "by": by, "year": year, "topics": topics, "start": start, "big": big, "ideas": ideas, "use": use, **({"note": note} if note else {})})
for m in MINDS:
    id_, name, role, topics, big, ideas, fun = m[:7]
    group = m[7] if len(m) > 7 else "business"
    assert all(t in TOPICS for t in topics), (id_, topics)
    out.append({"id": id_, "type": "mind", "tab": "marketer" if group == "marketing" else "mind", "group": group, "name": name, "by": role, "topics": topics, "big": big, "ideas": ideas, **({"fun": fun} if fun else {})})
ids = [x["id"] for x in out]
assert len(ids) == len(set(ids)), "duplicate id"
LABELS = {"offers": "Offers", "pricing": "Pricing", "marketing": "Marketing", "ads": "Ads", "copywriting": "Copywriting", "brand": "Personal brand", "sales": "Sales", "customers": "Customers", "startup": "Starting up", "ecommerce": "E-commerce", "strategy": "Strategy", "systems": "Systems", "money": "Money", "investing": "Investing", "mindset": "Mindset", "habits": "Habits", "negotiation": "Negotiation", "leadership": "Leadership", "story": "Stories", "psychology": "Psychology"}
assert set(LABELS) == set(TOPICS)
json.dump({"version": 2, "topics": TOPICS, "topicLabels": LABELS,
  "tabs": [{"id": "book", "label": "Books", "index": "Books"}, {"id": "mind", "label": "Great minds", "index": "Great minds"}, {"id": "marketer", "label": "Marketing geniuses", "index": "Marketing geniuses"}],
  "askBook": "What can I use from {name} for my business right now?", "askMind": "What would {name} tell me to do with my business right now?",
  "promptNote": "For marketing, ads, copy and brand questions, think like these marketing geniuses and say whose idea you're using.",
  "items": out}, sys.stdout, ensure_ascii=False, separators=(",", ":"))
sys.stderr.write(f"{sum(1 for x in out if x['type']=='book')} books, {sum(1 for x in out if x['type']=='mind' and x['group']=='business')} minds, {sum(1 for x in out if x['type']=='mind' and x['group']=='marketing')} marketing geniuses\n")
