# Summit's library: the key ideas of the best training, health and sports books, coaches, athletes and
# fitness creators, summarized in our own words. Build: python3 summit.py > ../summit-library.json
import json, sys

LABELS = {"strength": "Strength", "muscle": "Building muscle", "bodyweight": "Bodyweight", "mobility": "Mobility",
          "injury": "Staying injury-free", "cardio": "Cardio", "endurance": "Endurance",
          "basketball": "Basketball", "athletic": "Speed & jumps", "sleep": "Sleep", "nutrition": "Food",
          "recovery": "Recovery", "mindset": "Mindset", "habits": "Habits", "youth": "Young athletes"}
TOPICS = list(LABELS)

# (id, name, by, year, topics, start, big idea, ideas, when to use, [caution])
BOOKS = [
  ("young-athletes", "Strength Training for Young Athletes", "William J. Kraemer & Steven J. Fleck", 2005, ["youth", "strength", "injury"], True,
   "Strength training is safe and great for young athletes when it's supervised and technique comes first.",
   ["Learn the movement with light weight or bodyweight before adding load.",
    "Progress slowly: small increases, good form on every rep.",
    "Adult supervision and proper equipment make youth training safe.",
    "Stronger muscles and tendons help prevent sports injuries."],
   "Use it as the foundation for how you train at your age."),
  ("starting-strength", "Starting Strength", "Mark Rippetoe", 2005, ["strength"], False,
   "A few big barbell lifts, done well and made heavier slowly, build real strength.",
   ["Squat, deadlift, press and bench press cover most of the body.",
    "Add a little weight each session while form stays perfect.",
    "Technique is learned: film yourself and fix one thing at a time."],
   "Use it later, with a coach, when you move to barbell training.",
   "Barbell lifts at your age: only with a coach or adult watching, and never max attempts."),
  ("pyramid", "The Muscle and Strength Pyramid: Training", "Eric Helms, Andy Morgan & Andrea Valdez", 2015, ["muscle", "strength", "habits"], True,
   "Get the big things right first: consistency, then volume and effort, then the small details.",
   ["Adherence at the bottom: a plan you actually follow beats a perfect plan.",
    "Then volume, intensity and frequency; then progression; then exercise choice; then rest times and tempo.",
    "Don't major in the minors."],
   "Use it to know what really matters in training and what doesn't."),
  ("hypertrophy-schoenfeld", "Science and Development of Muscle Hypertrophy", "Brad Schoenfeld", 2016, ["muscle"], False,
   "Muscle grows from hard sets close to failure, enough weekly volume, and progress over time.",
   ["Mechanical tension is the main driver of muscle growth.",
    "A wide range of reps (about 6-30) builds muscle if sets are hard.",
    "Train each muscle about twice a week."],
   "Use it when you want the science behind building muscle."),
  ("rp-hypertrophy", "Scientific Principles of Hypertrophy Training", "Mike Israetel, James Hoffmann, Melissa Davis & Jared Feather", 2021, ["muscle", "recovery"], False,
   "Every muscle has a range of weekly sets: too few doesn't grow, too many can't be recovered from.",
   ["Volume landmarks: minimum effective volume up to maximum recoverable volume.",
    "Build up sets over a few weeks, then deload to recover.",
    "Pick exercises you can feel working and progress over time."],
   "Use it when planning how many sets to do per week."),
  ("built-from-broken", "Built from Broken", "Scott H. Hogan", 2021, ["injury", "mobility"], True,
   "Joints and tendons get stronger too, if you train them on purpose.",
   ["Tendons adapt slower than muscles: build up gradually.",
    "Train full range of motion, including end ranges, to protect joints.",
    "Small daily 'joint prep' work prevents big injuries."],
   "Use it if something aches (knees from basketball, for example) and to stay injury-free."),
  ("supple-leopard", "Becoming a Supple Leopard", "Kelly Starrett", 2013, ["mobility", "injury", "recovery"], False,
   "Good positions and daily mobility work let you move and perform better.",
   ["Organize your spine and joints before you lift or jump.",
    "Spend about 10 minutes a day on mobility for tight spots.",
    "Pain is a signal to fix position, not to push through."],
   "Use it to fix tight hips, ankles or shoulders."),
  ("back-mechanic", "Back Mechanic", "Stuart McGill", 2015, ["injury", "strength"], False,
   "A strong, stable core protects your back; learn to move from the hips.",
   ["The 'Big 3': curl-up, side plank and bird dog.",
    "Hinge at the hips and keep a neutral spine when lifting things.",
    "Avoid repeated heavy spine bending."],
   "Use it to keep your back healthy for life."),
  ("convict-conditioning", "Convict Conditioning", "Paul Wade", 2009, ["bodyweight", "strength"], True,
   "You can get very strong with bodyweight alone by following step-by-step progressions.",
   ["Six big moves: push-ups, squats, pull-ups, leg raises, bridges, handstand push-ups.",
    "Each has 10 steps from easy to very hard.",
    "Master each step before moving on."],
   "Use it to get strong at home with no equipment."),
  ("overcoming-gravity", "Overcoming Gravity", "Steven Low", 2011, ["bodyweight", "strength", "injury"], False,
   "A complete, careful system for gymnastics and calisthenics strength.",
   ["Plan progressions for skills like handstands, muscle-ups and levers.",
    "Build tendon strength slowly to avoid elbow and wrist injuries."],
   "Use it for calisthenics skills once the basics are solid."),
  ("endure", "Endure", "Alex Hutchinson", 2018, ["endurance", "mindset"], False,
   "Your brain sets limits before your body really runs out.",
   ["Belief and motivation change how hard effort feels.",
    "Smiling and positive self-talk can make hard work feel easier."],
   "Use it to push through the last minutes of a hard hike or game."),
  ("outlive", "Outlive", "Peter Attia", 2023, ["cardio", "strength", "habits"], False,
   "Train now for the body you want at 80: strength, stability and a big aerobic engine.",
   ["Zone 2 cardio (easy but steady) builds the base; some hard intervals raise your top end.",
    "Strength and balance protect you for life.",
    "Sleep and good food are part of training."],
   "Use it to understand why training every day matters for your whole life."),
  ("why-we-sleep", "Why We Sleep", "Matthew Walker", 2017, ["sleep", "recovery"], True,
   "Sleep is when your body and brain recover and grow.",
   ["Teenagers need about 8-10 hours of sleep.",
    "Regular sleep and wake times matter as much as total hours.",
    "Screens and caffeine late at night hurt sleep."],
   "Use it to take sleep as seriously as training.",
   "Some numbers in the book have been debated by scientists; the core message (sleep matters a lot) is solid."),
  ("mamba-mentality", "The Mamba Mentality", "Kobe Bryant", 2018, ["basketball", "mindset", "habits"], True,
   "Kobe's approach: obsessive preparation, studying the game, and loving the work.",
   ["Watch film of yourself and the best players to learn.",
    "Master the fundamentals until they're automatic.",
    "Prepare your body: strength and recovery were part of his daily routine."],
   "Use it for basketball and for the discipline to train every day."),
  ("relentless", "Relentless", "Tim S. Grover", 2013, ["mindset", "basketball"], False,
   "The trainer of Jordan and Kobe on what makes the greatest competitors different.",
   ["Great competitors keep going when everyone else stops.",
    "Control your emotions under pressure.",
    "Be obsessed with getting better, not with being praised."],
   "Use it for mental toughness in sports and business.",
   "Very intense in tone. Take the drive, not the idea that you must never rest: recovery matters."),
  ("jump-attack", "Jump Attack", "Tim S. Grover", 2000, ["athletic", "basketball"], False,
   "A structured program to jump higher using strength and explosive training.",
   ["Build strength first, then add explosive jumps.",
    "Quality over quantity: every jump at full effort, with good landings."],
   "Use it for dunking goals, carefully and with good landing technique."),
  ("range", "Range", "David Epstein", 2019, ["youth", "mindset", "athletic"], True,
   "Trying many sports and skills when young builds better athletes and thinkers.",
   ["Most top athletes played many sports as kids before specializing.",
    "Variety builds coordination and prevents overuse injuries.",
    "It's fine not to know your one thing yet."],
   "Use it to feel good about playing basketball and doing lots of other sports."),
  ("peak", "Peak", "Anders Ericsson & Robert Pool", 2016, ["habits", "mindset", "basketball"], False,
   "Experts are made by deliberate practice: focused work on weaknesses with feedback.",
   ["Practice just outside your comfort zone.",
    "Get fast feedback (a coach, video) and fix one thing at a time.",
    "Hours alone don't make you great; focused hours do."],
   "Use it to improve skills like shooting or dribbling faster."),
  ("champions-mind", "The Champion's Mind", "Jim Afremow", 2014, ["mindset"], False,
   "The mental habits of champions: confidence, focus and handling pressure.",
   ["Focus on the process you control, not the result.",
    "Use a short routine before shots or big moments.",
    "Talk to yourself like a coach, not a critic."],
   "Use it before games and tryouts."),
  ("mindset-dweck", "Mindset", "Carol S. Dweck", 2006, ["mindset", "youth"], True,
   "Believing you can improve (a growth mindset) makes you improve more.",
   ["Abilities grow with effort, strategy and help from others.",
    "Mistakes are information, not proof you're bad at something.",
    "Praise effort and strategy, not talent."],
   "Use it whenever something feels too hard: 'not yet' instead of 'can't'."),
  ("spark", "Spark", "John J. Ratey", 2008, ["cardio", "habits"], False,
   "Exercise makes your brain sharper, happier and better at learning.",
   ["Cardio before studying can boost focus.",
    "Exercise reduces stress and improves mood."],
   "Use it as a reason to work out before homework."),
  ("atomic-habits-summit", "Atomic Habits", "James Clear", 2018, ["habits"], True,
   "Tiny improvements, done every day, add up to huge results.",
   ["Make training obvious, attractive, easy and satisfying.",
    "Never miss twice: one missed workout is fine, two starts a new habit.",
    "Identity: 'I'm an athlete who trains every day.'"],
   "Use it to never skip your daily workout."),
  ("cant-hurt-me", "Can't Hurt Me", "David Goggins", 2018, ["mindset"], False,
   "When you think you're done, you're only about 40% done.",
   ["Callous your mind by doing hard things on purpose.",
    "Take an honest look in the mirror: own your weaknesses.",
    "Keep a 'cookie jar' of past wins to remember in hard moments."],
   "Use it for mental toughness.",
   "Goggins trained through serious injuries. Don't copy his extremes: pain that is sharp or in a joint means stop."),
  ("food-rules", "Food Rules", "Michael Pollan", 2009, ["nutrition"], True,
   "Eat food. Not too much. Mostly plants.",
   ["Eat real food, mostly things your grandparents would recognize.",
    "Eat lots of plants, plus good protein.",
    "Enjoy meals with family, slowly."],
   "Use it for simple, healthy eating without dieting."),
]

# (id, name, role, topics, big idea, ideas, fun fact, [caution])
COACHES = [
  ("israetel", "Dr. Mike Israetel", "Sport scientist, Renaissance Periodization", ["muscle", "recovery"],
   "Train hard enough, with enough volume, and recover well: that's the whole game.",
   ["Stimulus, fatigue, recovery: balance all three.",
    "Most sets should end 1-3 reps from failure.",
    "Deload every few weeks."], ""),
  ("schoenfeld-mind", "Brad Schoenfeld", "Muscle-growth researcher", ["muscle"],
   "Many rep ranges build muscle when sets are hard.",
   ["Twice a week per muscle beats once.",
    "Full range of motion usually works best."], ""),
  ("helms-mind", "Eric Helms", "Coach and researcher, natural bodybuilding", ["muscle", "nutrition", "habits"],
   "Consistency is the foundation; details come last.",
   ["Progress slowly and sustainably.",
    "Natural athletes should set realistic expectations and be patient."], ""),
  ("mcgill-mind", "Stuart McGill", "Spine scientist", ["injury", "strength"],
   "Stiffen the core to move the limbs: protect your back for life.",
   ["The Big 3 exercises daily.",
    "Train the core to resist movement, not only to create it."], ""),
  ("starrett-mind", "Kelly Starrett", "Physical therapist, mobility coach", ["mobility", "recovery"],
   "Ten minutes of mobility a day keeps your body moving well.",
   ["Test and retest: try a mobility drill and see if you move better.",
    "Sleep, walking and good positions are recovery tools."], ""),
  ("huberman", "Andrew Huberman", "Neuroscientist, podcaster", ["sleep", "recovery", "habits"],
   "Morning sunlight and regular sleep times set your body clock.",
   ["Get outside light soon after waking.",
    "Keep bedtime and wake time steady, even on weekends.",
    "Exercise and sleep are the biggest levers for health."], "",
   "Skip his supplement talk at your age: food, sleep and training are enough."),
  ("attia-mind", "Peter Attia", "Longevity doctor", ["cardio", "strength"],
   "Build strength, stability and aerobic fitness now for a long, active life.",
   ["Zone 2 cardio as a base.",
    "Grip strength and balance matter more than people think."], ""),
  ("grover-mind", "Tim Grover", "Trainer of Michael Jordan and Kobe Bryant", ["basketball", "mindset", "athletic"],
   "The greatest competitors are relentless about the work nobody sees.",
   ["Train your body so your skills hold up in the fourth quarter.",
    "Be comfortable being uncomfortable."], ""),
  ("rippetoe-mind", "Mark Rippetoe", "Strength coach", ["strength"],
   "Strong people are harder to kill and more useful in general.",
   ["Learn the big lifts with perfect form.",
    "Add a little weight regularly."], ""),
  ("defranco", "Joe DeFranco", "Athletic performance coach", ["athletic", "mobility", "strength"],
   "Athletes need strength, speed, mobility and conditioning together.",
   ["His 'Limber 11' is a quick mobility routine for athletes.",
    "Train to be athletic, not just to look strong."], ""),
]

ATHLETES = [
  ("kobe", "Kobe Bryant", "5× NBA champion", ["basketball", "mindset", "habits"],
   "Love the process so much that the hard work feels like play.",
   ["Famous for training before sunrise.",
    "Studied film of himself and of legends to learn.",
    "Mastered one move at a time until it was perfect."], ""),
  ("jordan", "Michael Jordan", "6× NBA champion", ["basketball", "mindset"],
   "Failure is part of success: he missed thousands of shots and kept shooting.",
   ["Was cut from his high school varsity team and used it as fuel.",
    "Competed hard in every practice, not just games."],
   "Didn't make his high school varsity team as a sophomore."),
  ("curry", "Stephen Curry", "4× NBA champion, greatest shooter ever", ["basketball", "athletic", "habits"],
   "Skill comes from thousands of focused reps, and small players can change the game.",
   ["Rebuilt his shot as a teenager, even though it was hard.",
    "Uses creative drills that train vision and handling at the same time.",
    "Was told he was too small; proved everyone wrong with skill."], ""),
  ("lebron", "LeBron James", "4× NBA champion", ["recovery", "basketball", "sleep"],
   "Take care of your body like a business: recovery is training.",
   ["Prioritizes 8-10 hours of sleep.",
    "Invests heavily in recovery, mobility and nutrition to play for 20+ years."], ""),
  ("kipchoge", "Eliud Kipchoge", "Marathon legend", ["endurance", "mindset", "habits"],
   "No human is limited. Discipline is doing what you should, even when you don't feel like it.",
   ["Consistency over years: he keeps a simple, steady routine.",
    "Logs every training session in a notebook.",
    "Trains hard but mostly smart and easy."], ""),
  ("goggins-mind", "David Goggins", "Ultra-endurance athlete, ex-Navy SEAL", ["mindset"],
   "When your mind says you're done, you still have more in you.",
   ["Do something hard every day to build mental toughness.",
    "Hold yourself accountable honestly."], "",
   "Don't copy his extremes. Sharp pain or joint pain means stop and rest."),
]

# (id, name, what they do, topics, big idea, ideas, fun fact, [caution])
CREATORS = [
  ("nippard", "Jeff Nippard", "Science-based lifting YouTuber", ["muscle", "strength"],
   "Train with the research on your side: the most effective exercises and set ranges, explained simply.",
   ["Pick exercises that stretch the muscle under load.",
    "Progressive overload: add a rep or a little weight over time.",
    "Most people need more consistency, not more exercises."],
   "Studied biochemistry and competed as a natural powerlifter and bodybuilder."),
  ("ethier", "Jeremy Ethier", "Built With Science", ["muscle", "injury", "bodyweight"],
   "Clear, evidence-based workouts, including great ones you can do at home.",
   ["Good form and full range beat heavy ego lifting.",
    "Home workouts can build muscle if you progress them."], ""),
  ("athleanx", "Jeff Cavaliere (Athlean-X)", "Physical therapist and trainer", ["injury", "athletic", "strength"],
   "Train like an athlete, and fix imbalances before they become injuries.",
   ["Balance pushing with pulling to protect your shoulders.",
    "Build strength and athleticism together."],
   "Was the head physical therapist and strength coach for the New York Mets."),
  ("tennyson", "Will Tennyson", "Fitness and food YouTuber", ["nutrition", "habits"],
   "Fitness can be fun: he tries famous athletes' diets and workouts and shows what really happens.",
   ["Make training and eating well something you enjoy.",
    "Sees for himself what works rather than believing hype."], "",
   "Some videos show huge eating challenges or strict diets: entertainment, not a plan for you."),
  ("hybrid-calisthenics", "Hampton Liu (Hybrid Calisthenics)", "Calisthenics YouTuber", ["bodyweight", "habits", "mindset"],
   "Anyone can start from zero with bodyweight training, one easy step at a time.",
   ["Start with the easiest version and progress when it feels good.",
    "Kind, positive self-talk keeps you training.",
    "Great beginner routines with no equipment."], ""),
  ("squat-u", "Aaron Horschig (Squat University)", "Physical therapist", ["injury", "mobility", "strength"],
   "Move well before you move heavy.",
   ["Test your ankle and hip mobility.",
    "Fix the cause of pain, not only the spot that hurts."], ""),
  ("david-laid", "David Laid", "Fitness creator", ["muscle", "mindset", "youth"],
   "Started lifting as a skinny teenager and documented years of steady progress.",
   ["Consistency over years beats any shortcut.",
    "Enjoy the process of getting a little better every month."],
   "Began training around 14 and became famous for his transformation videos.",
   "His physique took many years; compare yourself to your own past, not to him."),
  ("cbum", "Chris Bumstead (CBum)", "6× Mr. Olympia Classic Physique champion", ["muscle", "mindset", "habits"],
   "Discipline, patience and mental health all matter on the way to your goals.",
   ["Show up even on bad days.",
    "Talks openly about mental health, which is part of being strong."], "",
   "A pro bodybuilder's body is not a goal for a teenager. Take the discipline, not the physique target."),
]

out = []
def add(tab, rows, kind):
    for r in rows:
        if kind == "book":
            id_, name, by, year, topics, start, big, ideas, use = r[:9]; note = r[9] if len(r) > 9 else ""
            item = {"id": id_, "type": "book", "tab": tab, "name": name, "by": by, "year": year, "topics": topics, "start": start, "big": big, "ideas": ideas, "use": use}
        else:
            id_, name, role, topics, big, ideas, fun = r[:7]; note = r[7] if len(r) > 7 else ""
            item = {"id": id_, "type": "mind", "tab": tab, "name": name, "by": role, "topics": topics, "big": big, "ideas": ideas}
            if fun: item["fun"] = fun
        if note: item["note"] = note
        assert all(t in TOPICS for t in topics), (id_, topics)
        out.append(item)
add("book", BOOKS, "book"); add("coach", COACHES, "mind"); add("athlete", ATHLETES, "mind"); add("creator", CREATORS, "mind")
ids = [x["id"] for x in out]; assert len(ids) == len(set(ids)), "duplicate id"
json.dump({"version": 2, "topics": TOPICS, "topicLabels": LABELS,
  "tabs": [{"id": "book", "label": "Books", "index": "Books"}, {"id": "coach", "label": "Coaches & scientists", "index": "Coaches and scientists"},
           {"id": "athlete", "label": "Legendary athletes", "index": "Legendary athletes"}, {"id": "creator", "label": "Fitness creators", "index": "Fitness creators"}],
  "askBook": "What can I use from {name} in my training right now?", "askMind": "What would {name} tell me to do in my training right now?",
  "promptNote": "Ground training advice in these sources and say whose idea you're using. Creators are for motivation and ideas; the science and coaches come first. Always adapt to their age.",
  "items": out}, sys.stdout, ensure_ascii=False, separators=(",", ":"))
sys.stderr.write(", ".join(f"{sum(1 for x in out if x['tab']==t)} {t}" for t in ["book", "coach", "athlete", "creator"]) + "\n")
